# Created 2017-05-05 Fri 10:33
#+TITLE: Contributing Guide
#+AUTHOR: Kaushal Modi
This guide is for you if you'd like to do any of the below:
- Open an issue (plus provide debug information).
- Simply clone this repo and build =eless= locally.
- Do above + Provide a PR.
* How to help debug
- If you find =eless= not working as expected, file an [[https://github.com/kaushalmodi/eless/issues][issue]].
- Include the following debug information:
  1. =emacs --version=
  2. =eless= debug info:
     - Append the =-D= option to your =eless= use case. Examples:
       - =eless foo -D=
       - =info org | eless -D=
     - If you are providing debug info for something like =man foo=, do
       - =PAGER=​"eless -D" man foo=
* Development
** Dependencies
There are virtually no dependencies, except of course that you need
org.

I used the latest emacs and org-mode versions built from their master
branches for this project. So if any of the below steps do not work
for you, open an issue.

Talking about dependencies, this project builds *everything* from
=eless.org= file, the =eless= script /plus/ all the HTML, Info
documentation, =README.org=, =CONTRIBUTING.org=, and even the Wiki
pages. So before running =M-x eless-build= mentioned in below build
steps, you need to:
#+BEGIN_SRC shell
cd doc/
git clone https://github.com/kaushalmodi/eless.wiki.git
#+END_SRC
** Steps to build =eless= and documentation
- Open =eless.org=.
  - You will be prompted to mark certain /Local Variables/ settings as
    safe:
    #+BEGIN_SRC emacs-lisp
    (org-confirm-babel-evaluate lambda
                                (lang body)
                                (let
                                    ((unsafe t))
                                  (when
                                      (or
                                       (string= lang "org")
                                       (string= body "git rev-parse HEAD | head -c 7"))
                                    (setq unsafe nil))
                                  unsafe))
    (eval load
          (expand-file-name "build/build.el"))
    (org-html-htmlize-font-prefix . "org-")
    (org-html-htmlize-output-type . css)
    (org-src-preserve-indentation . t)
    #+END_SRC
  - Approving that permanently will exclamation mark will ensure that
    the =build.el= gets loaded each time you open =eless.org=. In
    addition it also enables auto-evaluating of the =git rev-parse
        HEAD= command and setting of few org variables.
- Do =M-x eless-build=. /This command got defined when the
  =build/build.el= got auto-loaded in the above step./
- Run the tangled =eless= through [[http://www.shellcheck.net/][shellcheck]] to ensure that there are
  no errors.
- Understand the changes made in =eless=, /plus/ all the other files.
- Provide a PR.
- If changes are only to the Wiki, I believe you can push them
  directly using =git= or manually edit those [[https://github.com/kaushalmodi/eless/wiki][here]]. /I have to yet
  figure out how to keep the non-git Wiki changes and changes in
  =eless.org= in sync./
